# Generated by Django 2.1.5 on 2022-04-21 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220421_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 22, 12, 11, 835190)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 22, 12, 11, 835190)),
        ),
    ]
