# Generated by Django 2.1.5 on 2022-04-22 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220421_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 1, 8, 38, 30912)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 1, 8, 38, 30912)),
        ),
    ]
